spring.application.name=progress-management-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/progress-management-3
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

# access-token
# eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwidXNlcm5hbWUiOiJob2FuZ252IiwiZW1haWwiOiJob2FuZy5uZ3V5ZW5AZXhhbXBsZS5jb20iLCJyb2xlcyI6IlJPTEVfQURNSU4iLCJpYXQiOjE3ODU3NDkzODIsImV4cCI6MTc4NTgzNTc4Mn0.ahQppHbXtxQylY5wi49BNwZhEMC2W1Vw05mmveNRcRgqAv6rQYCPkjAYKAPmABUs